[tools]
kubectl = "1.35.3"
helm    = "3.20.1"
k3d     = "5.8.3"
argocd  = "3.2.9"
sops    = "3.12.2"
age     = "1.3.1"
"ubi:argoproj/argo-rollouts" = { version = "1.8.3", exe = "kubectl-argo-rollouts" }
"github:hatoo/oha" = "1.14.0"
gh      = "2.87.2"
